# @generated by rules_jsonschema//tools/schema_to_starlark. DO NOT EDIT.
#
# Source schema: aws-s3-bucket.json
#
# Refresh via the generating rule's `update` script;
# the diff_test will fail until you do.

load("@rules_jsonschema//runtime:helpers.bzl", "parse_json_or_none", "strip_empty")

CloudformationAwsS3BucketInfo = provider(
    doc = "A bucket contributed by a target. Shard JSON matches the bucket schema.",
    fields = {
        "bucket_name": "string: top-level key for this bucket in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_s3_bucket_impl(ctx):
    item_name = ctx.attr.bucket_name or ctx.label.name
    payload = {
        "AbacStatus": ctx.attr.AbacStatus,
        "AccelerateConfiguration": parse_json_or_none(ctx.attr.AccelerateConfiguration),
        "AccessControl": ctx.attr.AccessControl,
        "AnalyticsConfigurations": parse_json_or_none(ctx.attr.AnalyticsConfigurations),
        "Arn": ctx.attr.Arn,
        "BucketEncryption": parse_json_or_none(ctx.attr.BucketEncryption),
        "BucketName": ctx.attr.BucketName,
        "BucketNamePrefix": ctx.attr.BucketNamePrefix,
        "BucketNamespace": ctx.attr.BucketNamespace,
        "CorsConfiguration": parse_json_or_none(ctx.attr.CorsConfiguration),
        "DomainName": ctx.attr.DomainName,
        "DualStackDomainName": ctx.attr.DualStackDomainName,
        "IntelligentTieringConfigurations": parse_json_or_none(ctx.attr.IntelligentTieringConfigurations),
        "InventoryConfigurations": parse_json_or_none(ctx.attr.InventoryConfigurations),
        "LifecycleConfiguration": parse_json_or_none(ctx.attr.LifecycleConfiguration),
        "LoggingConfiguration": parse_json_or_none(ctx.attr.LoggingConfiguration),
        "MetadataConfiguration": parse_json_or_none(ctx.attr.MetadataConfiguration),
        "MetadataTableConfiguration": parse_json_or_none(ctx.attr.MetadataTableConfiguration),
        "MetricsConfigurations": parse_json_or_none(ctx.attr.MetricsConfigurations),
        "NotificationConfiguration": parse_json_or_none(ctx.attr.NotificationConfiguration),
        "ObjectLockConfiguration": parse_json_or_none(ctx.attr.ObjectLockConfiguration),
        "ObjectLockEnabled": ctx.attr.ObjectLockEnabled,
        "OwnershipControls": parse_json_or_none(ctx.attr.OwnershipControls),
        "PublicAccessBlockConfiguration": parse_json_or_none(ctx.attr.PublicAccessBlockConfiguration),
        "RegionalDomainName": ctx.attr.RegionalDomainName,
        "ReplicationConfiguration": parse_json_or_none(ctx.attr.ReplicationConfiguration),
        "Tags": parse_json_or_none(ctx.attr.Tags),
        "VersioningConfiguration": parse_json_or_none(ctx.attr.VersioningConfiguration),
        "WebsiteConfiguration": parse_json_or_none(ctx.attr.WebsiteConfiguration),
        "WebsiteURL": ctx.attr.WebsiteURL,
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".bucket.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsS3BucketInfo(bucket_name = item_name, json = shard),
    ]

cloudformation_aws_s3_bucket = rule(
    implementation = _cloudformation_aws_s3_bucket_impl,
    doc = "The ``AWS::S3::Bucket`` resource creates an Amazon S3 bucket in the same AWS Region where you create the AWS CloudFormation stack.  To control how AWS CloudFormation handles the bucket when the stack is deleted, you can set a deletion policy for your bucket. You can choose to *retain* the bucket or to *delete* the bucket. For more information, see [DeletionPolicy Attribute](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-attribute-deletionpolicy.html).   You can only delete empty buckets. Deletion fails for buckets that have contents.",
    provides = [CloudformationAwsS3BucketInfo],
    attrs = {
        "bucket_name": attr.string(
            doc = "Top-level key for this bucket in the rendered project. Defaults to the rule name.",
        ),
        "AbacStatus": attr.string(
            values = ["Enabled", "Disabled"],
            doc = "The ABAC status of the general purpose bucket. When ABAC is enabled for the general purpose bucket, you can use tags to manage access to the general purpose buckets as well as for cost tracking purposes. When ABAC is disabled for the general purpose buckets, you can only use tags for cost tracking purposes. For more information, see [Using tags with S3 general purpose buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/buckets-tagging.html).",
        ),
        "AccelerateConfiguration": attr.string(
            doc = "Configures the transfer acceleration state for an Amazon S3 bucket. For more information, see [Amazon S3 Transfer Acceleration](https://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html) in the *Amazon S3 User Guide*. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "AccessControl": attr.string(
            values = ["AuthenticatedRead", "AwsExecRead", "BucketOwnerFullControl", "BucketOwnerRead", "LogDeliveryWrite", "Private", "PublicRead", "PublicReadWrite"],
            doc = "This is a legacy property, and it is not recommended for most use cases. A majority of modern use cases in Amazon S3 no longer require the use of ACLs, and we recommend that you keep ACLs disabled. For more information, see [Controlling object ownership](https://docs.aws.amazon.com//AmazonS3/latest/userguide/about-object-ownership.html) in the *Amazon S3 User Guide*.   A canned access control list (ACL) that grants predefined permissions to the bucket. For more information about canned ACLs, see [Canned ACL](https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl) in the *Amazon S3 User Guide*.   S3 buckets are created with ACLs disabled by default. Therefore, unless you explicitly set the [AWS::S3::OwnershipControls](https://docs.aws.amazon.com//AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-ownershipcontrols.html) property to enable ACLs, your resource will fail to deploy with any value other than Private. Use cases requiring ACLs are uncommon.   The majority of access control configurations can be successfully and more easily achieved with bucket policies. For more information, see [AWS::S3::BucketPolicy](https://docs.aws.amazon.com//AWSCloudFormation/latest/UserGuide/aws-properties-s3-policy.html). For examples of common policy configurations, including S3 Server Access Logs buckets and more, see [Bucket policy examples](https://docs.aws.amazon.com/AmazonS3/latest/userguide/example-bucket-policies.html) in the *Amazon S3 User Guide*.",
        ),
        "AnalyticsConfigurations": attr.string(
            doc = "Specifies the configuration and any analyses for the analytics filter of an Amazon S3 bucket. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Arn": attr.string(),
        "BucketEncryption": attr.string(
            doc = "Specifies default encryption for a bucket using server-side encryption with Amazon S3-managed keys (SSE-S3), AWS KMS-managed keys (SSE-KMS), or dual-layer server-side encryption with KMS-managed keys (DSSE-KMS). For information about the Amazon S3 default encryption feature, see [Amazon S3 Default Encryption for S3 Buckets](https://docs.aws.amazon.com/AmazonS3/latest/dev/bucket-encryption.html) in the *Amazon S3 User Guide*. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "BucketName": attr.string(
            doc = "A name for the bucket. If you don't specify a name, AWS CloudFormation generates a unique ID and uses that ID for the bucket name. The bucket name must contain only lowercase letters, numbers, periods (.), and dashes (-) and must follow [Amazon S3 bucket restrictions and limitations](https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html). For more information, see [Rules for naming Amazon S3 buckets](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) in the *Amazon S3 User Guide*.    If you specify a name, you can't perform updates that require replacement of this resource. You can perform updates that require no or some interruption. If you need to replace the resource, specify a new name.",
        ),
        "BucketNamePrefix": attr.string(),
        "BucketNamespace": attr.string(
            values = ["global", "account-regional"],),
        "CorsConfiguration": attr.string(
            doc = "Describes the cross-origin access configuration for objects in an Amazon S3 bucket. For more information, see [Enabling Cross-Origin Resource Sharing](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html) in the *Amazon S3 User Guide*. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "DomainName": attr.string(),
        "DualStackDomainName": attr.string(),
        "IntelligentTieringConfigurations": attr.string(
            doc = "Defines how Amazon S3 handles Intelligent-Tiering storage. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "InventoryConfigurations": attr.string(
            doc = "Specifies the S3 Inventory configuration for an Amazon S3 bucket. For more information, see [GET Bucket inventory](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGETInventoryConfig.html) in the *Amazon S3 API Reference*. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "LifecycleConfiguration": attr.string(
            doc = "Specifies the lifecycle configuration for objects in an Amazon S3 bucket. For more information, see [Object Lifecycle Management](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html) in the *Amazon S3 User Guide*. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "LoggingConfiguration": attr.string(
            doc = "Settings that define where logs are stored. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "MetadataConfiguration": attr.string(
            doc = "The S3 Metadata configuration for a general purpose bucket. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "MetadataTableConfiguration": attr.string(
            doc = "The metadata table configuration of an S3 general purpose bucket. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "MetricsConfigurations": attr.string(
            doc = "Specifies a metrics configuration for the CloudWatch request metrics (specified by the metrics configuration ID) from an Amazon S3 bucket. If you're updating an existing metrics configuration, note that this is a full replacement of the existing metrics configuration. If you don't include the elements you want to keep, they are erased. For more information, see [PutBucketMetricsConfiguration](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTMetricConfiguration.html). (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "NotificationConfiguration": attr.string(
            doc = "Configuration that defines how Amazon S3 handles bucket notifications. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "ObjectLockConfiguration": attr.string(
            doc = "This operation is not supported for directory buckets.   Places an Object Lock configuration on the specified bucket. The rule specified in the Object Lock configuration will be applied by default to every new object placed in the specified bucket. For more information, see [Locking Objects](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lock.html).     +  The ``DefaultRetention`` settings require both a mode and a period.   +  The ``DefaultRetention`` period can be either ``Days`` or ``Years`` but you must select one. You cannot specify ``Days`` and ``Years`` at the same time.   +  You can enable Object Lock for new or existing buckets. For more information, see [Configuring Object Lock](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lock-configure.html).       You must URL encode any signed header values that contain spaces. For example, if your header value is ``my file.txt``, containing two spaces after ``my``, you must URL encode this value to ``my%20%20file.txt``. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "ObjectLockEnabled": attr.bool(
            doc = "Indicates whether this bucket has an Object Lock configuration enabled. Enable ``ObjectLockEnabled`` when you apply ``ObjectLockConfiguration`` to a bucket.",
        ),
        "OwnershipControls": attr.string(
            doc = "Configuration that defines how Amazon S3 handles Object Ownership rules. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "PublicAccessBlockConfiguration": attr.string(
            doc = "Configuration that defines how Amazon S3 handles public access. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "RegionalDomainName": attr.string(),
        "ReplicationConfiguration": attr.string(
            doc = "Configuration for replicating objects in an S3 bucket. To enable replication, you must also enable versioning by using the ``VersioningConfiguration`` property.  Amazon S3 can store replicated objects in a single destination bucket or multiple destination buckets. The destination bucket or buckets must already exist. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Tags": attr.string(
            doc = "An arbitrary set of tags (key-value pairs) for this S3 bucket. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "VersioningConfiguration": attr.string(
            doc = "Enables multiple versions of all objects in this bucket. You might enable versioning to prevent objects from being deleted or overwritten by mistake or to archive objects so that you can retrieve previous versions of them.   When you enable versioning on a bucket for the first time, it might take a short amount of time for the change to be fully propagated. We recommend that you wait for 15 minutes after enabling versioning before issuing write operations (``PUT`` or ``DELETE``) on objects in the bucket. (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "WebsiteConfiguration": attr.string(
            doc = "Information used to configure the bucket as a static website. For more information, see [Hosting Websites on Amazon S3](https://docs.aws.amazon.com/AmazonS3/latest/dev/WebsiteHosting.html). (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "WebsiteURL": attr.string(),
    },
)

