# @generated by rules_jsonschema//tools/schema_to_starlark. DO NOT EDIT.
#
# Source schema: storage-spec.json
#
# Refresh via the generating rule's `update` script;
# the diff_test will fail until you do.

load("@rules_jsonschema//runtime:helpers.bzl", "parse_json_or_none", "strip_empty")

CloudformationAwsS3BucketInfo = provider(
    doc = "A bucket contributed by a target. Shard JSON matches the bucket schema.",
    fields = {
        "bucket_name": "string: top-level key for this bucket in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_s3_bucket_impl(ctx):
    item_name = ctx.attr.bucket_name or ctx.label.name
    payload = {
        "AbacStatus": ctx.attr.AbacStatus,
        "AccelerateConfiguration": parse_json_or_none(ctx.attr.AccelerateConfiguration),
        "AccessControl": ctx.attr.AccessControl,
        "AnalyticsConfigurations": parse_json_or_none(ctx.attr.AnalyticsConfigurations),
        "BucketEncryption": parse_json_or_none(ctx.attr.BucketEncryption),
        "BucketName": ctx.attr.BucketName,
        "BucketNamePrefix": ctx.attr.BucketNamePrefix,
        "BucketNamespace": ctx.attr.BucketNamespace,
        "CorsConfiguration": parse_json_or_none(ctx.attr.CorsConfiguration),
        "IntelligentTieringConfigurations": parse_json_or_none(ctx.attr.IntelligentTieringConfigurations),
        "InventoryConfigurations": parse_json_or_none(ctx.attr.InventoryConfigurations),
        "LifecycleConfiguration": parse_json_or_none(ctx.attr.LifecycleConfiguration),
        "LoggingConfiguration": parse_json_or_none(ctx.attr.LoggingConfiguration),
        "MetadataConfiguration": parse_json_or_none(ctx.attr.MetadataConfiguration),
        "MetadataTableConfiguration": parse_json_or_none(ctx.attr.MetadataTableConfiguration),
        "MetricsConfigurations": parse_json_or_none(ctx.attr.MetricsConfigurations),
        "NotificationConfiguration": parse_json_or_none(ctx.attr.NotificationConfiguration),
        "ObjectLockConfiguration": parse_json_or_none(ctx.attr.ObjectLockConfiguration),
        "ObjectLockEnabled": parse_json_or_none(ctx.attr.ObjectLockEnabled),
        "OwnershipControls": parse_json_or_none(ctx.attr.OwnershipControls),
        "PublicAccessBlockConfiguration": parse_json_or_none(ctx.attr.PublicAccessBlockConfiguration),
        "ReplicationConfiguration": parse_json_or_none(ctx.attr.ReplicationConfiguration),
        "Tags": parse_json_or_none(ctx.attr.Tags),
        "VersioningConfiguration": parse_json_or_none(ctx.attr.VersioningConfiguration),
        "WebsiteConfiguration": parse_json_or_none(ctx.attr.WebsiteConfiguration),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".bucket.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsS3BucketInfo(bucket_name = item_name, json = shard),
    ]

cloudformation_aws_s3_bucket = rule(
    implementation = _cloudformation_aws_s3_bucket_impl,
    doc = "Schema-derived rule for one `bucket` entry.",
    provides = [CloudformationAwsS3BucketInfo],
    attrs = {
        "bucket_name": attr.string(
            doc = "Top-level key for this bucket in the rendered project. Defaults to the rule name.",
        ),
        "AbacStatus": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-abacstatus",
        ),
        "AccelerateConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "AccessControl": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-accesscontrol",
        ),
        "AnalyticsConfigurations": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-analyticsconfigurations (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "BucketEncryption": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "BucketName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-bucketname",
        ),
        "BucketNamePrefix": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-bucketnameprefix",
        ),
        "BucketNamespace": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-bucketnamespace",
        ),
        "CorsConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "IntelligentTieringConfigurations": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-intelligenttieringconfigurations (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "InventoryConfigurations": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-inventoryconfigurations (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "LifecycleConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "LoggingConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "MetadataConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "MetadataTableConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "MetricsConfigurations": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-metricsconfigurations (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "NotificationConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "ObjectLockConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "ObjectLockEnabled": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-objectlockenabled (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "OwnershipControls": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "PublicAccessBlockConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "ReplicationConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-s3-bucket.html#cfn-s3-bucket-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "VersioningConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "WebsiteConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
    },
)

