# @generated by rules_jsonschema//tools/schema_to_starlark. DO NOT EDIT.
#
# Source schema: compute-spec.json
#
# Refresh via the generating rule's `update` script;
# the diff_test will fail until you do.

load("@rules_jsonschema//runtime:helpers.bzl", "parse_json_or_none", "strip_empty")

CloudformationAwsLambdaFunctionInfo = provider(
    doc = "A lambda_function contributed by a target. Shard JSON matches the lambda_function schema.",
    fields = {
        "lambda_function_name": "string: top-level key for this lambda_function in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_lambda_function_impl(ctx):
    item_name = ctx.attr.lambda_function_name or ctx.label.name
    payload = {
        "Architectures": parse_json_or_none(ctx.attr.Architectures),
        "CapacityProviderConfig": parse_json_or_none(ctx.attr.CapacityProviderConfig),
        "Code": parse_json_or_none(ctx.attr.Code),
        "CodeSigningConfigArn": ctx.attr.CodeSigningConfigArn,
        "DeadLetterConfig": parse_json_or_none(ctx.attr.DeadLetterConfig),
        "Description": ctx.attr.Description,
        "DurableConfig": parse_json_or_none(ctx.attr.DurableConfig),
        "Environment": parse_json_or_none(ctx.attr.Environment),
        "EphemeralStorage": parse_json_or_none(ctx.attr.EphemeralStorage),
        "FileSystemConfigs": parse_json_or_none(ctx.attr.FileSystemConfigs),
        "FunctionName": ctx.attr.FunctionName,
        "FunctionScalingConfig": parse_json_or_none(ctx.attr.FunctionScalingConfig),
        "Handler": ctx.attr.Handler,
        "ImageConfig": parse_json_or_none(ctx.attr.ImageConfig),
        "KmsKeyArn": ctx.attr.KmsKeyArn,
        "Layers": parse_json_or_none(ctx.attr.Layers),
        "LoggingConfig": parse_json_or_none(ctx.attr.LoggingConfig),
        "MemorySize": parse_json_or_none(ctx.attr.MemorySize),
        "PackageType": ctx.attr.PackageType,
        "PublishToLatestPublished": parse_json_or_none(ctx.attr.PublishToLatestPublished),
        "RecursiveLoop": ctx.attr.RecursiveLoop,
        "ReservedConcurrentExecutions": parse_json_or_none(ctx.attr.ReservedConcurrentExecutions),
        "Role": ctx.attr.Role,
        "Runtime": ctx.attr.Runtime,
        "RuntimeManagementConfig": parse_json_or_none(ctx.attr.RuntimeManagementConfig),
        "SnapStart": parse_json_or_none(ctx.attr.SnapStart),
        "Tags": parse_json_or_none(ctx.attr.Tags),
        "TenancyConfig": parse_json_or_none(ctx.attr.TenancyConfig),
        "Timeout": parse_json_or_none(ctx.attr.Timeout),
        "TracingConfig": parse_json_or_none(ctx.attr.TracingConfig),
        "VpcConfig": parse_json_or_none(ctx.attr.VpcConfig),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".lambda_function.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsLambdaFunctionInfo(lambda_function_name = item_name, json = shard),
    ]

cloudformation_aws_lambda_function = rule(
    implementation = _cloudformation_aws_lambda_function_impl,
    doc = "Schema-derived rule for one `lambda_function` entry.",
    provides = [CloudformationAwsLambdaFunctionInfo],
    attrs = {
        "lambda_function_name": attr.string(
            doc = "Top-level key for this lambda_function in the rendered project. Defaults to the rule name.",
        ),
        "Architectures": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-architectures (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "CapacityProviderConfig": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "Code": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "CodeSigningConfigArn": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-codesigningconfigarn",
        ),
        "DeadLetterConfig": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "Description": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-description",
        ),
        "DurableConfig": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "Environment": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "EphemeralStorage": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "FileSystemConfigs": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-filesystemconfigs (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "FunctionName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-functionname",
        ),
        "FunctionScalingConfig": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "Handler": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-handler",
        ),
        "ImageConfig": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "KmsKeyArn": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-kmskeyarn",
        ),
        "Layers": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-layers (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "LoggingConfig": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "MemorySize": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-memorysize (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "PackageType": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-packagetype",
        ),
        "PublishToLatestPublished": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-publishtolatestpublished (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "RecursiveLoop": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-recursiveloop",
        ),
        "ReservedConcurrentExecutions": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-reservedconcurrentexecutions (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Role": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-role",
        ),
        "Runtime": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-runtime",
        ),
        "RuntimeManagementConfig": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "SnapStart": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "TenancyConfig": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "Timeout": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-timeout (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "TracingConfig": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "VpcConfig": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
    },
)

CloudformationAwsLambdaPermissionInfo = provider(
    doc = "A lambda_permission contributed by a target. Shard JSON matches the lambda_permission schema.",
    fields = {
        "lambda_permission_name": "string: top-level key for this lambda_permission in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_lambda_permission_impl(ctx):
    item_name = ctx.attr.lambda_permission_name or ctx.label.name
    payload = {
        "Action": ctx.attr.Action,
        "EventSourceToken": ctx.attr.EventSourceToken,
        "FunctionName": ctx.attr.FunctionName,
        "FunctionUrlAuthType": ctx.attr.FunctionUrlAuthType,
        "InvokedViaFunctionUrl": parse_json_or_none(ctx.attr.InvokedViaFunctionUrl),
        "Principal": ctx.attr.Principal,
        "PrincipalOrgID": ctx.attr.PrincipalOrgID,
        "SourceAccount": ctx.attr.SourceAccount,
        "SourceArn": ctx.attr.SourceArn,
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".lambda_permission.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsLambdaPermissionInfo(lambda_permission_name = item_name, json = shard),
    ]

cloudformation_aws_lambda_permission = rule(
    implementation = _cloudformation_aws_lambda_permission_impl,
    doc = "Schema-derived rule for one `lambda_permission` entry.",
    provides = [CloudformationAwsLambdaPermissionInfo],
    attrs = {
        "lambda_permission_name": attr.string(
            doc = "Top-level key for this lambda_permission in the rendered project. Defaults to the rule name.",
        ),
        "Action": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html#cfn-lambda-permission-action",
        ),
        "EventSourceToken": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html#cfn-lambda-permission-eventsourcetoken",
        ),
        "FunctionName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html#cfn-lambda-permission-functionname",
        ),
        "FunctionUrlAuthType": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html#cfn-lambda-permission-functionurlauthtype",
        ),
        "InvokedViaFunctionUrl": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html#cfn-lambda-permission-invokedviafunctionurl (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Principal": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html#cfn-lambda-permission-principal",
        ),
        "PrincipalOrgID": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html#cfn-lambda-permission-principalorgid",
        ),
        "SourceAccount": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html#cfn-lambda-permission-sourceaccount",
        ),
        "SourceArn": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-permission.html#cfn-lambda-permission-sourcearn",
        ),
    },
)

CloudformationAwsEcsServiceInfo = provider(
    doc = "A ecs_service contributed by a target. Shard JSON matches the ecs_service schema.",
    fields = {
        "ecs_service_name": "string: top-level key for this ecs_service in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_ecs_service_impl(ctx):
    item_name = ctx.attr.ecs_service_name or ctx.label.name
    payload = {
        "AvailabilityZoneRebalancing": ctx.attr.AvailabilityZoneRebalancing,
        "CapacityProviderStrategy": parse_json_or_none(ctx.attr.CapacityProviderStrategy),
        "Cluster": ctx.attr.Cluster,
        "DeploymentConfiguration": parse_json_or_none(ctx.attr.DeploymentConfiguration),
        "DeploymentController": parse_json_or_none(ctx.attr.DeploymentController),
        "DesiredCount": parse_json_or_none(ctx.attr.DesiredCount),
        "EnableECSManagedTags": parse_json_or_none(ctx.attr.EnableECSManagedTags),
        "EnableExecuteCommand": parse_json_or_none(ctx.attr.EnableExecuteCommand),
        "ForceNewDeployment": parse_json_or_none(ctx.attr.ForceNewDeployment),
        "HealthCheckGracePeriodSeconds": parse_json_or_none(ctx.attr.HealthCheckGracePeriodSeconds),
        "LaunchType": ctx.attr.LaunchType,
        "LoadBalancers": parse_json_or_none(ctx.attr.LoadBalancers),
        "NetworkConfiguration": parse_json_or_none(ctx.attr.NetworkConfiguration),
        "PlacementConstraints": parse_json_or_none(ctx.attr.PlacementConstraints),
        "PlacementStrategies": parse_json_or_none(ctx.attr.PlacementStrategies),
        "PlatformVersion": ctx.attr.PlatformVersion,
        "PropagateTags": ctx.attr.PropagateTags,
        "Role": ctx.attr.Role,
        "SchedulingStrategy": ctx.attr.SchedulingStrategy,
        "ServiceConnectConfiguration": parse_json_or_none(ctx.attr.ServiceConnectConfiguration),
        "ServiceName": ctx.attr.ServiceName,
        "ServiceRegistries": parse_json_or_none(ctx.attr.ServiceRegistries),
        "Tags": parse_json_or_none(ctx.attr.Tags),
        "TaskDefinition": ctx.attr.TaskDefinition,
        "VolumeConfigurations": parse_json_or_none(ctx.attr.VolumeConfigurations),
        "VpcLatticeConfigurations": parse_json_or_none(ctx.attr.VpcLatticeConfigurations),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".ecs_service.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsEcsServiceInfo(ecs_service_name = item_name, json = shard),
    ]

cloudformation_aws_ecs_service = rule(
    implementation = _cloudformation_aws_ecs_service_impl,
    doc = "Schema-derived rule for one `ecs_service` entry.",
    provides = [CloudformationAwsEcsServiceInfo],
    attrs = {
        "ecs_service_name": attr.string(
            doc = "Top-level key for this ecs_service in the rendered project. Defaults to the rule name.",
        ),
        "AvailabilityZoneRebalancing": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-availabilityzonerebalancing",
        ),
        "CapacityProviderStrategy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-capacityproviderstrategy (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Cluster": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-cluster",
        ),
        "DeploymentConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "DeploymentController": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "DesiredCount": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-desiredcount (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "EnableECSManagedTags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-enableecsmanagedtags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "EnableExecuteCommand": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-enableexecutecommand (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "ForceNewDeployment": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "HealthCheckGracePeriodSeconds": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-healthcheckgraceperiodseconds (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "LaunchType": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-launchtype",
        ),
        "LoadBalancers": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-loadbalancers (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "NetworkConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "PlacementConstraints": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-placementconstraints (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "PlacementStrategies": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-placementstrategies (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "PlatformVersion": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-platformversion",
        ),
        "PropagateTags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-propagatetags",
        ),
        "Role": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-role",
        ),
        "SchedulingStrategy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-schedulingstrategy",
        ),
        "ServiceConnectConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "ServiceName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-servicename",
        ),
        "ServiceRegistries": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-serviceregistries (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "TaskDefinition": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-taskdefinition",
        ),
        "VolumeConfigurations": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-volumeconfigurations (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "VpcLatticeConfigurations": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-service.html#cfn-ecs-service-vpclatticeconfigurations (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

CloudformationAwsEcsClusterInfo = provider(
    doc = "A ecs_cluster contributed by a target. Shard JSON matches the ecs_cluster schema.",
    fields = {
        "ecs_cluster_name": "string: top-level key for this ecs_cluster in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_ecs_cluster_impl(ctx):
    item_name = ctx.attr.ecs_cluster_name or ctx.label.name
    payload = {
        "CapacityProviders": parse_json_or_none(ctx.attr.CapacityProviders),
        "ClusterName": ctx.attr.ClusterName,
        "ClusterSettings": parse_json_or_none(ctx.attr.ClusterSettings),
        "Configuration": parse_json_or_none(ctx.attr.Configuration),
        "DefaultCapacityProviderStrategy": parse_json_or_none(ctx.attr.DefaultCapacityProviderStrategy),
        "ServiceConnectDefaults": parse_json_or_none(ctx.attr.ServiceConnectDefaults),
        "Tags": parse_json_or_none(ctx.attr.Tags),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".ecs_cluster.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsEcsClusterInfo(ecs_cluster_name = item_name, json = shard),
    ]

cloudformation_aws_ecs_cluster = rule(
    implementation = _cloudformation_aws_ecs_cluster_impl,
    doc = "Schema-derived rule for one `ecs_cluster` entry.",
    provides = [CloudformationAwsEcsClusterInfo],
    attrs = {
        "ecs_cluster_name": attr.string(
            doc = "Top-level key for this ecs_cluster in the rendered project. Defaults to the rule name.",
        ),
        "CapacityProviders": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html#cfn-ecs-cluster-capacityproviders (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "ClusterName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html#cfn-ecs-cluster-clustername",
        ),
        "ClusterSettings": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html#cfn-ecs-cluster-clustersettings (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Configuration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "DefaultCapacityProviderStrategy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html#cfn-ecs-cluster-defaultcapacityproviderstrategy (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "ServiceConnectDefaults": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-cluster.html#cfn-ecs-cluster-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

CloudformationAwsEcsTaskDefinitionInfo = provider(
    doc = "A ecs_task_definition contributed by a target. Shard JSON matches the ecs_task_definition schema.",
    fields = {
        "ecs_task_definition_name": "string: top-level key for this ecs_task_definition in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_ecs_task_definition_impl(ctx):
    item_name = ctx.attr.ecs_task_definition_name or ctx.label.name
    payload = {
        "ContainerDefinitions": parse_json_or_none(ctx.attr.ContainerDefinitions),
        "Cpu": ctx.attr.Cpu,
        "EnableFaultInjection": parse_json_or_none(ctx.attr.EnableFaultInjection),
        "EphemeralStorage": parse_json_or_none(ctx.attr.EphemeralStorage),
        "ExecutionRoleArn": ctx.attr.ExecutionRoleArn,
        "Family": ctx.attr.Family,
        "IpcMode": ctx.attr.IpcMode,
        "Memory": ctx.attr.Memory,
        "NetworkMode": ctx.attr.NetworkMode,
        "PidMode": ctx.attr.PidMode,
        "PlacementConstraints": parse_json_or_none(ctx.attr.PlacementConstraints),
        "ProxyConfiguration": parse_json_or_none(ctx.attr.ProxyConfiguration),
        "RequiresCompatibilities": parse_json_or_none(ctx.attr.RequiresCompatibilities),
        "RuntimePlatform": parse_json_or_none(ctx.attr.RuntimePlatform),
        "Tags": parse_json_or_none(ctx.attr.Tags),
        "TaskRoleArn": ctx.attr.TaskRoleArn,
        "Volumes": parse_json_or_none(ctx.attr.Volumes),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".ecs_task_definition.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsEcsTaskDefinitionInfo(ecs_task_definition_name = item_name, json = shard),
    ]

cloudformation_aws_ecs_task_definition = rule(
    implementation = _cloudformation_aws_ecs_task_definition_impl,
    doc = "Schema-derived rule for one `ecs_task_definition` entry.",
    provides = [CloudformationAwsEcsTaskDefinitionInfo],
    attrs = {
        "ecs_task_definition_name": attr.string(
            doc = "Top-level key for this ecs_task_definition in the rendered project. Defaults to the rule name.",
        ),
        "ContainerDefinitions": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-containerdefinitions (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Cpu": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-cpu",
        ),
        "EnableFaultInjection": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-enablefaultinjection (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "EphemeralStorage": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "ExecutionRoleArn": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-executionrolearn",
        ),
        "Family": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-family",
        ),
        "IpcMode": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-ipcmode",
        ),
        "Memory": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-memory",
        ),
        "NetworkMode": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-networkmode",
        ),
        "PidMode": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-pidmode",
        ),
        "PlacementConstraints": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-placementconstraints (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "ProxyConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "RequiresCompatibilities": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-requirescompatibilities (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "RuntimePlatform": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "TaskRoleArn": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-taskrolearn",
        ),
        "Volumes": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecs-taskdefinition.html#cfn-ecs-taskdefinition-volumes (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

CloudformationAwsEcrRepositoryInfo = provider(
    doc = "A ecr_repository contributed by a target. Shard JSON matches the ecr_repository schema.",
    fields = {
        "ecr_repository_name": "string: top-level key for this ecr_repository in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_ecr_repository_impl(ctx):
    item_name = ctx.attr.ecr_repository_name or ctx.label.name
    payload = {
        "EmptyOnDelete": parse_json_or_none(ctx.attr.EmptyOnDelete),
        "EncryptionConfiguration": parse_json_or_none(ctx.attr.EncryptionConfiguration),
        "ImageScanningConfiguration": parse_json_or_none(ctx.attr.ImageScanningConfiguration),
        "ImageTagMutability": ctx.attr.ImageTagMutability,
        "ImageTagMutabilityExclusionFilters": parse_json_or_none(ctx.attr.ImageTagMutabilityExclusionFilters),
        "LifecyclePolicy": parse_json_or_none(ctx.attr.LifecyclePolicy),
        "RepositoryName": ctx.attr.RepositoryName,
        "RepositoryPolicyText": parse_json_or_none(ctx.attr.RepositoryPolicyText),
        "Tags": parse_json_or_none(ctx.attr.Tags),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".ecr_repository.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsEcrRepositoryInfo(ecr_repository_name = item_name, json = shard),
    ]

cloudformation_aws_ecr_repository = rule(
    implementation = _cloudformation_aws_ecr_repository_impl,
    doc = "Schema-derived rule for one `ecr_repository` entry.",
    provides = [CloudformationAwsEcrRepositoryInfo],
    attrs = {
        "ecr_repository_name": attr.string(
            doc = "Top-level key for this ecr_repository in the rendered project. Defaults to the rule name.",
        ),
        "EmptyOnDelete": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-emptyondelete (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "EncryptionConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "ImageScanningConfiguration": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "ImageTagMutability": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-imagetagmutability",
        ),
        "ImageTagMutabilityExclusionFilters": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-imagetagmutabilityexclusionfilters (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "LifecyclePolicy": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "RepositoryName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-repositoryname",
        ),
        "RepositoryPolicyText": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-repositorypolicytext (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-ecr-repository.html#cfn-ecr-repository-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

