# @generated by rules_jsonschema//tools/schema_to_starlark. DO NOT EDIT.
#
# Source schema: database-spec.json
#
# Refresh via the generating rule's `update` script;
# the diff_test will fail until you do.

load("@rules_jsonschema//runtime:helpers.bzl", "parse_json_or_none", "strip_empty")

CloudformationAwsDynamodbTableInfo = provider(
    doc = "A dynamodb_table contributed by a target. Shard JSON matches the dynamodb_table schema.",
    fields = {
        "dynamodb_table_name": "string: top-level key for this dynamodb_table in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_dynamodb_table_impl(ctx):
    item_name = ctx.attr.dynamodb_table_name or ctx.label.name
    payload = {
        "AttributeDefinitions": parse_json_or_none(ctx.attr.AttributeDefinitions),
        "BillingMode": ctx.attr.BillingMode,
        "ContributorInsightsSpecification": parse_json_or_none(ctx.attr.ContributorInsightsSpecification),
        "DeletionProtectionEnabled": parse_json_or_none(ctx.attr.DeletionProtectionEnabled),
        "GlobalSecondaryIndexes": parse_json_or_none(ctx.attr.GlobalSecondaryIndexes),
        "ImportSourceSpecification": parse_json_or_none(ctx.attr.ImportSourceSpecification),
        "KeySchema": parse_json_or_none(ctx.attr.KeySchema),
        "KinesisStreamSpecification": parse_json_or_none(ctx.attr.KinesisStreamSpecification),
        "LocalSecondaryIndexes": parse_json_or_none(ctx.attr.LocalSecondaryIndexes),
        "OnDemandThroughput": parse_json_or_none(ctx.attr.OnDemandThroughput),
        "PointInTimeRecoverySpecification": parse_json_or_none(ctx.attr.PointInTimeRecoverySpecification),
        "ProvisionedThroughput": parse_json_or_none(ctx.attr.ProvisionedThroughput),
        "ResourcePolicy": parse_json_or_none(ctx.attr.ResourcePolicy),
        "SSESpecification": parse_json_or_none(ctx.attr.SSESpecification),
        "StreamSpecification": parse_json_or_none(ctx.attr.StreamSpecification),
        "TableClass": ctx.attr.TableClass,
        "TableName": ctx.attr.TableName,
        "Tags": parse_json_or_none(ctx.attr.Tags),
        "TimeToLiveSpecification": parse_json_or_none(ctx.attr.TimeToLiveSpecification),
        "WarmThroughput": parse_json_or_none(ctx.attr.WarmThroughput),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".dynamodb_table.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsDynamodbTableInfo(dynamodb_table_name = item_name, json = shard),
    ]

cloudformation_aws_dynamodb_table = rule(
    implementation = _cloudformation_aws_dynamodb_table_impl,
    doc = "Schema-derived rule for one `dynamodb_table` entry.",
    provides = [CloudformationAwsDynamodbTableInfo],
    attrs = {
        "dynamodb_table_name": attr.string(
            doc = "Top-level key for this dynamodb_table in the rendered project. Defaults to the rule name.",
        ),
        "AttributeDefinitions": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-attributedefinitions (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "BillingMode": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-billingmode",
        ),
        "ContributorInsightsSpecification": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "DeletionProtectionEnabled": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-deletionprotectionenabled (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "GlobalSecondaryIndexes": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-globalsecondaryindexes (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "ImportSourceSpecification": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "KeySchema": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-keyschema (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "KinesisStreamSpecification": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "LocalSecondaryIndexes": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-localsecondaryindexes (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "OnDemandThroughput": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "PointInTimeRecoverySpecification": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "ProvisionedThroughput": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "ResourcePolicy": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "SSESpecification": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "StreamSpecification": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "TableClass": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-tableclass",
        ),
        "TableName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-tablename",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#cfn-dynamodb-table-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "TimeToLiveSpecification": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "WarmThroughput": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
    },
)

CloudformationAwsDynamodbGlobalTableInfo = provider(
    doc = "A dynamodb_global_table contributed by a target. Shard JSON matches the dynamodb_global_table schema.",
    fields = {
        "dynamodb_global_table_name": "string: top-level key for this dynamodb_global_table in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_dynamodb_global_table_impl(ctx):
    item_name = ctx.attr.dynamodb_global_table_name or ctx.label.name
    payload = {
        "AttributeDefinitions": parse_json_or_none(ctx.attr.AttributeDefinitions),
        "BillingMode": ctx.attr.BillingMode,
        "GlobalSecondaryIndexes": parse_json_or_none(ctx.attr.GlobalSecondaryIndexes),
        "GlobalTableSourceArn": ctx.attr.GlobalTableSourceArn,
        "GlobalTableWitnesses": parse_json_or_none(ctx.attr.GlobalTableWitnesses),
        "KeySchema": parse_json_or_none(ctx.attr.KeySchema),
        "LocalSecondaryIndexes": parse_json_or_none(ctx.attr.LocalSecondaryIndexes),
        "MultiRegionConsistency": ctx.attr.MultiRegionConsistency,
        "ReadOnDemandThroughputSettings": parse_json_or_none(ctx.attr.ReadOnDemandThroughputSettings),
        "ReadProvisionedThroughputSettings": parse_json_or_none(ctx.attr.ReadProvisionedThroughputSettings),
        "Replicas": parse_json_or_none(ctx.attr.Replicas),
        "SSESpecification": parse_json_or_none(ctx.attr.SSESpecification),
        "StreamSpecification": parse_json_or_none(ctx.attr.StreamSpecification),
        "TableName": ctx.attr.TableName,
        "TimeToLiveSpecification": parse_json_or_none(ctx.attr.TimeToLiveSpecification),
        "WarmThroughput": parse_json_or_none(ctx.attr.WarmThroughput),
        "WriteOnDemandThroughputSettings": parse_json_or_none(ctx.attr.WriteOnDemandThroughputSettings),
        "WriteProvisionedThroughputSettings": parse_json_or_none(ctx.attr.WriteProvisionedThroughputSettings),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".dynamodb_global_table.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsDynamodbGlobalTableInfo(dynamodb_global_table_name = item_name, json = shard),
    ]

cloudformation_aws_dynamodb_global_table = rule(
    implementation = _cloudformation_aws_dynamodb_global_table_impl,
    doc = "Schema-derived rule for one `dynamodb_global_table` entry.",
    provides = [CloudformationAwsDynamodbGlobalTableInfo],
    attrs = {
        "dynamodb_global_table_name": attr.string(
            doc = "Top-level key for this dynamodb_global_table in the rendered project. Defaults to the rule name.",
        ),
        "AttributeDefinitions": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-globaltable.html#cfn-dynamodb-globaltable-attributedefinitions (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "BillingMode": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-globaltable.html#cfn-dynamodb-globaltable-billingmode",
        ),
        "GlobalSecondaryIndexes": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-globaltable.html#cfn-dynamodb-globaltable-globalsecondaryindexes (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "GlobalTableSourceArn": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-globaltable.html#cfn-dynamodb-globaltable-globaltablesourcearn",
        ),
        "GlobalTableWitnesses": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-globaltable.html#cfn-dynamodb-globaltable-globaltablewitnesses (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "KeySchema": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-globaltable.html#cfn-dynamodb-globaltable-keyschema (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "LocalSecondaryIndexes": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-globaltable.html#cfn-dynamodb-globaltable-localsecondaryindexes (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "MultiRegionConsistency": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-globaltable.html#cfn-dynamodb-globaltable-multiregionconsistency",
        ),
        "ReadOnDemandThroughputSettings": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "ReadProvisionedThroughputSettings": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "Replicas": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-globaltable.html#cfn-dynamodb-globaltable-replicas (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "SSESpecification": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "StreamSpecification": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "TableName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-globaltable.html#cfn-dynamodb-globaltable-tablename",
        ),
        "TimeToLiveSpecification": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "WarmThroughput": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "WriteOnDemandThroughputSettings": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "WriteProvisionedThroughputSettings": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
    },
)

