# @generated by rules_jsonschema//tools/schema_to_starlark. DO NOT EDIT.
#
# Source schema: identity-spec.json
#
# Refresh via the generating rule's `update` script;
# the diff_test will fail until you do.

load("@rules_jsonschema//runtime:helpers.bzl", "parse_json_or_none", "strip_empty")

CloudformationAwsIamRoleInfo = provider(
    doc = "A iam_role contributed by a target. Shard JSON matches the iam_role schema.",
    fields = {
        "iam_role_name": "string: top-level key for this iam_role in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_iam_role_impl(ctx):
    item_name = ctx.attr.iam_role_name or ctx.label.name
    payload = {
        "AssumeRolePolicyDocument": parse_json_or_none(ctx.attr.AssumeRolePolicyDocument),
        "Description": ctx.attr.Description,
        "ManagedPolicyArns": parse_json_or_none(ctx.attr.ManagedPolicyArns),
        "MaxSessionDuration": parse_json_or_none(ctx.attr.MaxSessionDuration),
        "Path": ctx.attr.Path,
        "PermissionsBoundary": ctx.attr.PermissionsBoundary,
        "Policies": parse_json_or_none(ctx.attr.Policies),
        "RoleName": ctx.attr.RoleName,
        "Tags": parse_json_or_none(ctx.attr.Tags),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".iam_role.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsIamRoleInfo(iam_role_name = item_name, json = shard),
    ]

cloudformation_aws_iam_role = rule(
    implementation = _cloudformation_aws_iam_role_impl,
    doc = "Schema-derived rule for one `iam_role` entry.",
    provides = [CloudformationAwsIamRoleInfo],
    attrs = {
        "iam_role_name": attr.string(
            doc = "Top-level key for this iam_role in the rendered project. Defaults to the rule name.",
        ),
        "AssumeRolePolicyDocument": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-assumerolepolicydocument (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Description": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-description",
        ),
        "ManagedPolicyArns": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-managedpolicyarns (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "MaxSessionDuration": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-maxsessionduration (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Path": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-path",
        ),
        "PermissionsBoundary": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-permissionsboundary",
        ),
        "Policies": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-policies (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "RoleName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-rolename",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

CloudformationAwsIamPolicyInfo = provider(
    doc = "A iam_policy contributed by a target. Shard JSON matches the iam_policy schema.",
    fields = {
        "iam_policy_name": "string: top-level key for this iam_policy in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_iam_policy_impl(ctx):
    item_name = ctx.attr.iam_policy_name or ctx.label.name
    payload = {
        "Groups": parse_json_or_none(ctx.attr.Groups),
        "PolicyDocument": parse_json_or_none(ctx.attr.PolicyDocument),
        "PolicyName": ctx.attr.PolicyName,
        "Roles": parse_json_or_none(ctx.attr.Roles),
        "Users": parse_json_or_none(ctx.attr.Users),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".iam_policy.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsIamPolicyInfo(iam_policy_name = item_name, json = shard),
    ]

cloudformation_aws_iam_policy = rule(
    implementation = _cloudformation_aws_iam_policy_impl,
    doc = "Schema-derived rule for one `iam_policy` entry.",
    provides = [CloudformationAwsIamPolicyInfo],
    attrs = {
        "iam_policy_name": attr.string(
            doc = "Top-level key for this iam_policy in the rendered project. Defaults to the rule name.",
        ),
        "Groups": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html#cfn-iam-policy-groups (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "PolicyDocument": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html#cfn-iam-policy-policydocument (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "PolicyName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html#cfn-iam-policy-policyname",
        ),
        "Roles": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html#cfn-iam-policy-roles (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Users": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html#cfn-iam-policy-users (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

CloudformationAwsIamManagedPolicyInfo = provider(
    doc = "A iam_managed_policy contributed by a target. Shard JSON matches the iam_managed_policy schema.",
    fields = {
        "iam_managed_policy_name": "string: top-level key for this iam_managed_policy in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_iam_managed_policy_impl(ctx):
    item_name = ctx.attr.iam_managed_policy_name or ctx.label.name
    payload = {
        "Description": ctx.attr.Description,
        "Groups": parse_json_or_none(ctx.attr.Groups),
        "ManagedPolicyName": ctx.attr.ManagedPolicyName,
        "Path": ctx.attr.Path,
        "PolicyDocument": parse_json_or_none(ctx.attr.PolicyDocument),
        "Roles": parse_json_or_none(ctx.attr.Roles),
        "Users": parse_json_or_none(ctx.attr.Users),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".iam_managed_policy.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsIamManagedPolicyInfo(iam_managed_policy_name = item_name, json = shard),
    ]

cloudformation_aws_iam_managed_policy = rule(
    implementation = _cloudformation_aws_iam_managed_policy_impl,
    doc = "Schema-derived rule for one `iam_managed_policy` entry.",
    provides = [CloudformationAwsIamManagedPolicyInfo],
    attrs = {
        "iam_managed_policy_name": attr.string(
            doc = "Top-level key for this iam_managed_policy in the rendered project. Defaults to the rule name.",
        ),
        "Description": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html#cfn-iam-managedpolicy-description",
        ),
        "Groups": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html#cfn-iam-managedpolicy-groups (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "ManagedPolicyName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html#cfn-iam-managedpolicy-managedpolicyname",
        ),
        "Path": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html#cfn-iam-managedpolicy-path",
        ),
        "PolicyDocument": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html#cfn-iam-managedpolicy-policydocument (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Roles": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html#cfn-iam-managedpolicy-roles (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Users": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-managedpolicy.html#cfn-iam-managedpolicy-users (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

CloudformationAwsIamUserInfo = provider(
    doc = "A iam_user contributed by a target. Shard JSON matches the iam_user schema.",
    fields = {
        "iam_user_name": "string: top-level key for this iam_user in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_iam_user_impl(ctx):
    item_name = ctx.attr.iam_user_name or ctx.label.name
    payload = {
        "Groups": parse_json_or_none(ctx.attr.Groups),
        "LoginProfile": parse_json_or_none(ctx.attr.LoginProfile),
        "ManagedPolicyArns": parse_json_or_none(ctx.attr.ManagedPolicyArns),
        "Path": ctx.attr.Path,
        "PermissionsBoundary": ctx.attr.PermissionsBoundary,
        "Policies": parse_json_or_none(ctx.attr.Policies),
        "Tags": parse_json_or_none(ctx.attr.Tags),
        "UserName": ctx.attr.UserName,
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".iam_user.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsIamUserInfo(iam_user_name = item_name, json = shard),
    ]

cloudformation_aws_iam_user = rule(
    implementation = _cloudformation_aws_iam_user_impl,
    doc = "Schema-derived rule for one `iam_user` entry.",
    provides = [CloudformationAwsIamUserInfo],
    attrs = {
        "iam_user_name": attr.string(
            doc = "Top-level key for this iam_user in the rendered project. Defaults to the rule name.",
        ),
        "Groups": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-user.html#cfn-iam-user-groups (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "LoginProfile": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "ManagedPolicyArns": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-user.html#cfn-iam-user-managedpolicyarns (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Path": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-user.html#cfn-iam-user-path",
        ),
        "PermissionsBoundary": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-user.html#cfn-iam-user-permissionsboundary",
        ),
        "Policies": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-user.html#cfn-iam-user-policies (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-user.html#cfn-iam-user-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "UserName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-user.html#cfn-iam-user-username",
        ),
    },
)

CloudformationAwsIamGroupInfo = provider(
    doc = "A iam_group contributed by a target. Shard JSON matches the iam_group schema.",
    fields = {
        "iam_group_name": "string: top-level key for this iam_group in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_iam_group_impl(ctx):
    item_name = ctx.attr.iam_group_name or ctx.label.name
    payload = {
        "GroupName": ctx.attr.GroupName,
        "ManagedPolicyArns": parse_json_or_none(ctx.attr.ManagedPolicyArns),
        "Path": ctx.attr.Path,
        "Policies": parse_json_or_none(ctx.attr.Policies),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".iam_group.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsIamGroupInfo(iam_group_name = item_name, json = shard),
    ]

cloudformation_aws_iam_group = rule(
    implementation = _cloudformation_aws_iam_group_impl,
    doc = "Schema-derived rule for one `iam_group` entry.",
    provides = [CloudformationAwsIamGroupInfo],
    attrs = {
        "iam_group_name": attr.string(
            doc = "Top-level key for this iam_group in the rendered project. Defaults to the rule name.",
        ),
        "GroupName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-group.html#cfn-iam-group-groupname",
        ),
        "ManagedPolicyArns": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-group.html#cfn-iam-group-managedpolicyarns (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Path": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-group.html#cfn-iam-group-path",
        ),
        "Policies": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-group.html#cfn-iam-group-policies (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

