# @generated by rules_jsonschema//tools/schema_to_starlark. DO NOT EDIT.
#
# Source schema: messaging-spec.json
#
# Refresh via the generating rule's `update` script;
# the diff_test will fail until you do.

load("@rules_jsonschema//runtime:helpers.bzl", "parse_json_or_none", "strip_empty")

CloudformationAwsSqsQueueInfo = provider(
    doc = "A sqs_queue contributed by a target. Shard JSON matches the sqs_queue schema.",
    fields = {
        "sqs_queue_name": "string: top-level key for this sqs_queue in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_sqs_queue_impl(ctx):
    item_name = ctx.attr.sqs_queue_name or ctx.label.name
    payload = {
        "ContentBasedDeduplication": parse_json_or_none(ctx.attr.ContentBasedDeduplication),
        "DeduplicationScope": ctx.attr.DeduplicationScope,
        "DelaySeconds": parse_json_or_none(ctx.attr.DelaySeconds),
        "FifoQueue": parse_json_or_none(ctx.attr.FifoQueue),
        "FifoThroughputLimit": ctx.attr.FifoThroughputLimit,
        "KmsDataKeyReusePeriodSeconds": parse_json_or_none(ctx.attr.KmsDataKeyReusePeriodSeconds),
        "KmsMasterKeyId": ctx.attr.KmsMasterKeyId,
        "MaximumMessageSize": parse_json_or_none(ctx.attr.MaximumMessageSize),
        "MessageRetentionPeriod": parse_json_or_none(ctx.attr.MessageRetentionPeriod),
        "QueueName": ctx.attr.QueueName,
        "ReceiveMessageWaitTimeSeconds": parse_json_or_none(ctx.attr.ReceiveMessageWaitTimeSeconds),
        "RedriveAllowPolicy": parse_json_or_none(ctx.attr.RedriveAllowPolicy),
        "RedrivePolicy": parse_json_or_none(ctx.attr.RedrivePolicy),
        "SqsManagedSseEnabled": parse_json_or_none(ctx.attr.SqsManagedSseEnabled),
        "Tags": parse_json_or_none(ctx.attr.Tags),
        "VisibilityTimeout": parse_json_or_none(ctx.attr.VisibilityTimeout),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".sqs_queue.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsSqsQueueInfo(sqs_queue_name = item_name, json = shard),
    ]

cloudformation_aws_sqs_queue = rule(
    implementation = _cloudformation_aws_sqs_queue_impl,
    doc = "Schema-derived rule for one `sqs_queue` entry.",
    provides = [CloudformationAwsSqsQueueInfo],
    attrs = {
        "sqs_queue_name": attr.string(
            doc = "Top-level key for this sqs_queue in the rendered project. Defaults to the rule name.",
        ),
        "ContentBasedDeduplication": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-contentbaseddeduplication (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "DeduplicationScope": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-deduplicationscope",
        ),
        "DelaySeconds": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-delayseconds (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "FifoQueue": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-fifoqueue (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "FifoThroughputLimit": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-fifothroughputlimit",
        ),
        "KmsDataKeyReusePeriodSeconds": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-kmsdatakeyreuseperiodseconds (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "KmsMasterKeyId": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-kmsmasterkeyid",
        ),
        "MaximumMessageSize": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-maximummessagesize (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "MessageRetentionPeriod": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-messageretentionperiod (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "QueueName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-queuename",
        ),
        "ReceiveMessageWaitTimeSeconds": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-receivemessagewaittimeseconds (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "RedriveAllowPolicy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-redriveallowpolicy (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "RedrivePolicy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-redrivepolicy (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "SqsManagedSseEnabled": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-sqsmanagedsseenabled (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "VisibilityTimeout": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queue.html#cfn-sqs-queue-visibilitytimeout (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

CloudformationAwsSqsQueuePolicyInfo = provider(
    doc = "A sqs_queue_policy contributed by a target. Shard JSON matches the sqs_queue_policy schema.",
    fields = {
        "sqs_queue_policy_name": "string: top-level key for this sqs_queue_policy in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_sqs_queue_policy_impl(ctx):
    item_name = ctx.attr.sqs_queue_policy_name or ctx.label.name
    payload = {
        "PolicyDocument": parse_json_or_none(ctx.attr.PolicyDocument),
        "Queues": parse_json_or_none(ctx.attr.Queues),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".sqs_queue_policy.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsSqsQueuePolicyInfo(sqs_queue_policy_name = item_name, json = shard),
    ]

cloudformation_aws_sqs_queue_policy = rule(
    implementation = _cloudformation_aws_sqs_queue_policy_impl,
    doc = "Schema-derived rule for one `sqs_queue_policy` entry.",
    provides = [CloudformationAwsSqsQueuePolicyInfo],
    attrs = {
        "sqs_queue_policy_name": attr.string(
            doc = "Top-level key for this sqs_queue_policy in the rendered project. Defaults to the rule name.",
        ),
        "PolicyDocument": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queuepolicy.html#cfn-sqs-queuepolicy-policydocument (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Queues": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sqs-queuepolicy.html#cfn-sqs-queuepolicy-queues (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

CloudformationAwsSnsTopicInfo = provider(
    doc = "A sns_topic contributed by a target. Shard JSON matches the sns_topic schema.",
    fields = {
        "sns_topic_name": "string: top-level key for this sns_topic in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_sns_topic_impl(ctx):
    item_name = ctx.attr.sns_topic_name or ctx.label.name
    payload = {
        "ArchivePolicy": parse_json_or_none(ctx.attr.ArchivePolicy),
        "ContentBasedDeduplication": parse_json_or_none(ctx.attr.ContentBasedDeduplication),
        "DataProtectionPolicy": parse_json_or_none(ctx.attr.DataProtectionPolicy),
        "DeliveryStatusLogging": parse_json_or_none(ctx.attr.DeliveryStatusLogging),
        "DisplayName": ctx.attr.DisplayName,
        "FifoThroughputScope": ctx.attr.FifoThroughputScope,
        "FifoTopic": parse_json_or_none(ctx.attr.FifoTopic),
        "KmsMasterKeyId": ctx.attr.KmsMasterKeyId,
        "SignatureVersion": ctx.attr.SignatureVersion,
        "Subscription": parse_json_or_none(ctx.attr.Subscription),
        "Tags": parse_json_or_none(ctx.attr.Tags),
        "TopicName": ctx.attr.TopicName,
        "TracingConfig": ctx.attr.TracingConfig,
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".sns_topic.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsSnsTopicInfo(sns_topic_name = item_name, json = shard),
    ]

cloudformation_aws_sns_topic = rule(
    implementation = _cloudformation_aws_sns_topic_impl,
    doc = "Schema-derived rule for one `sns_topic` entry.",
    provides = [CloudformationAwsSnsTopicInfo],
    attrs = {
        "sns_topic_name": attr.string(
            doc = "Top-level key for this sns_topic in the rendered project. Defaults to the rule name.",
        ),
        "ArchivePolicy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-archivepolicy (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "ContentBasedDeduplication": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-contentbaseddeduplication (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "DataProtectionPolicy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-dataprotectionpolicy (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "DeliveryStatusLogging": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-deliverystatuslogging (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "DisplayName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-displayname",
        ),
        "FifoThroughputScope": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-fifothroughputscope",
        ),
        "FifoTopic": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-fifotopic (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "KmsMasterKeyId": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-kmsmasterkeyid",
        ),
        "SignatureVersion": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-signatureversion",
        ),
        "Subscription": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-subscription (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "TopicName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-topicname",
        ),
        "TracingConfig": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topic.html#cfn-sns-topic-tracingconfig",
        ),
    },
)

CloudformationAwsSnsSubscriptionInfo = provider(
    doc = "A sns_subscription contributed by a target. Shard JSON matches the sns_subscription schema.",
    fields = {
        "sns_subscription_name": "string: top-level key for this sns_subscription in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_sns_subscription_impl(ctx):
    item_name = ctx.attr.sns_subscription_name or ctx.label.name
    payload = {
        "DeliveryPolicy": parse_json_or_none(ctx.attr.DeliveryPolicy),
        "Endpoint": ctx.attr.Endpoint,
        "FilterPolicy": parse_json_or_none(ctx.attr.FilterPolicy),
        "FilterPolicyScope": ctx.attr.FilterPolicyScope,
        "Protocol": ctx.attr.Protocol,
        "RawMessageDelivery": parse_json_or_none(ctx.attr.RawMessageDelivery),
        "RedrivePolicy": parse_json_or_none(ctx.attr.RedrivePolicy),
        "Region": ctx.attr.Region,
        "ReplayPolicy": parse_json_or_none(ctx.attr.ReplayPolicy),
        "SubscriptionRoleArn": ctx.attr.SubscriptionRoleArn,
        "TopicArn": ctx.attr.TopicArn,
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".sns_subscription.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsSnsSubscriptionInfo(sns_subscription_name = item_name, json = shard),
    ]

cloudformation_aws_sns_subscription = rule(
    implementation = _cloudformation_aws_sns_subscription_impl,
    doc = "Schema-derived rule for one `sns_subscription` entry.",
    provides = [CloudformationAwsSnsSubscriptionInfo],
    attrs = {
        "sns_subscription_name": attr.string(
            doc = "Top-level key for this sns_subscription in the rendered project. Defaults to the rule name.",
        ),
        "DeliveryPolicy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-deliverypolicy (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Endpoint": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-endpoint",
        ),
        "FilterPolicy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-filterpolicy (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "FilterPolicyScope": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-filterpolicyscope",
        ),
        "Protocol": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-protocol",
        ),
        "RawMessageDelivery": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-rawmessagedelivery (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "RedrivePolicy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-redrivepolicy (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Region": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-region",
        ),
        "ReplayPolicy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-replaypolicy (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "SubscriptionRoleArn": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-subscriptionrolearn",
        ),
        "TopicArn": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-subscription.html#cfn-sns-subscription-topicarn",
        ),
    },
)

CloudformationAwsSnsTopicPolicyInfo = provider(
    doc = "A sns_topic_policy contributed by a target. Shard JSON matches the sns_topic_policy schema.",
    fields = {
        "sns_topic_policy_name": "string: top-level key for this sns_topic_policy in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_sns_topic_policy_impl(ctx):
    item_name = ctx.attr.sns_topic_policy_name or ctx.label.name
    payload = {
        "PolicyDocument": parse_json_or_none(ctx.attr.PolicyDocument),
        "Topics": parse_json_or_none(ctx.attr.Topics),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".sns_topic_policy.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsSnsTopicPolicyInfo(sns_topic_policy_name = item_name, json = shard),
    ]

cloudformation_aws_sns_topic_policy = rule(
    implementation = _cloudformation_aws_sns_topic_policy_impl,
    doc = "Schema-derived rule for one `sns_topic_policy` entry.",
    provides = [CloudformationAwsSnsTopicPolicyInfo],
    attrs = {
        "sns_topic_policy_name": attr.string(
            doc = "Top-level key for this sns_topic_policy in the rendered project. Defaults to the rule name.",
        ),
        "PolicyDocument": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topicpolicy.html#cfn-sns-topicpolicy-policydocument (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Topics": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sns-topicpolicy.html#cfn-sns-topicpolicy-topics (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

CloudformationAwsEventsEventBusInfo = provider(
    doc = "A events_event_bus contributed by a target. Shard JSON matches the events_event_bus schema.",
    fields = {
        "events_event_bus_name": "string: top-level key for this events_event_bus in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_events_event_bus_impl(ctx):
    item_name = ctx.attr.events_event_bus_name or ctx.label.name
    payload = {
        "DeadLetterConfig": parse_json_or_none(ctx.attr.DeadLetterConfig),
        "Description": ctx.attr.Description,
        "EventSourceName": ctx.attr.EventSourceName,
        "KmsKeyIdentifier": ctx.attr.KmsKeyIdentifier,
        "LogConfig": parse_json_or_none(ctx.attr.LogConfig),
        "Name": ctx.attr.Name,
        "Policy": parse_json_or_none(ctx.attr.Policy),
        "Tags": parse_json_or_none(ctx.attr.Tags),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".events_event_bus.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsEventsEventBusInfo(events_event_bus_name = item_name, json = shard),
    ]

cloudformation_aws_events_event_bus = rule(
    implementation = _cloudformation_aws_events_event_bus_impl,
    doc = "Schema-derived rule for one `events_event_bus` entry.",
    provides = [CloudformationAwsEventsEventBusInfo],
    attrs = {
        "events_event_bus_name": attr.string(
            doc = "Top-level key for this events_event_bus in the rendered project. Defaults to the rule name.",
        ),
        "DeadLetterConfig": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "Description": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbus.html#cfn-events-eventbus-description",
        ),
        "EventSourceName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbus.html#cfn-events-eventbus-eventsourcename",
        ),
        "KmsKeyIdentifier": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbus.html#cfn-events-eventbus-kmskeyidentifier",
        ),
        "LogConfig": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "Name": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbus.html#cfn-events-eventbus-name",
        ),
        "Policy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbus.html#cfn-events-eventbus-policy (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-eventbus.html#cfn-events-eventbus-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

CloudformationAwsEventsRuleInfo = provider(
    doc = "A events_rule contributed by a target. Shard JSON matches the events_rule schema.",
    fields = {
        "events_rule_name": "string: top-level key for this events_rule in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_events_rule_impl(ctx):
    item_name = ctx.attr.events_rule_name or ctx.label.name
    payload = {
        "Description": ctx.attr.Description,
        "EventBusName": ctx.attr.EventBusName,
        "EventPattern": parse_json_or_none(ctx.attr.EventPattern),
        "Name": ctx.attr.Name,
        "RoleArn": ctx.attr.RoleArn,
        "ScheduleExpression": ctx.attr.ScheduleExpression,
        "State": ctx.attr.State,
        "Tags": parse_json_or_none(ctx.attr.Tags),
        "Targets": parse_json_or_none(ctx.attr.Targets),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".events_rule.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsEventsRuleInfo(events_rule_name = item_name, json = shard),
    ]

cloudformation_aws_events_rule = rule(
    implementation = _cloudformation_aws_events_rule_impl,
    doc = "Schema-derived rule for one `events_rule` entry.",
    provides = [CloudformationAwsEventsRuleInfo],
    attrs = {
        "events_rule_name": attr.string(
            doc = "Top-level key for this events_rule in the rendered project. Defaults to the rule name.",
        ),
        "Description": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-description",
        ),
        "EventBusName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-eventbusname",
        ),
        "EventPattern": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-eventpattern (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Name": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-name",
        ),
        "RoleArn": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-rolearn",
        ),
        "ScheduleExpression": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-scheduleexpression",
        ),
        "State": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-state",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Targets": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-targets (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

