# @generated by rules_jsonschema//tools/schema_to_starlark. DO NOT EDIT.
#
# Source schema: observability-spec.json
#
# Refresh via the generating rule's `update` script;
# the diff_test will fail until you do.

load("@rules_jsonschema//runtime:helpers.bzl", "parse_json_or_none", "strip_empty")

CloudformationAwsLogsLogGroupInfo = provider(
    doc = "A logs_log_group contributed by a target. Shard JSON matches the logs_log_group schema.",
    fields = {
        "logs_log_group_name": "string: top-level key for this logs_log_group in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_logs_log_group_impl(ctx):
    item_name = ctx.attr.logs_log_group_name or ctx.label.name
    payload = {
        "BearerTokenAuthenticationEnabled": parse_json_or_none(ctx.attr.BearerTokenAuthenticationEnabled),
        "DataProtectionPolicy": parse_json_or_none(ctx.attr.DataProtectionPolicy),
        "DeletionProtectionEnabled": parse_json_or_none(ctx.attr.DeletionProtectionEnabled),
        "FieldIndexPolicies": parse_json_or_none(ctx.attr.FieldIndexPolicies),
        "KmsKeyId": ctx.attr.KmsKeyId,
        "LogGroupClass": ctx.attr.LogGroupClass,
        "LogGroupName": ctx.attr.LogGroupName,
        "ResourcePolicyDocument": parse_json_or_none(ctx.attr.ResourcePolicyDocument),
        "RetentionInDays": parse_json_or_none(ctx.attr.RetentionInDays),
        "Tags": parse_json_or_none(ctx.attr.Tags),
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".logs_log_group.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsLogsLogGroupInfo(logs_log_group_name = item_name, json = shard),
    ]

cloudformation_aws_logs_log_group = rule(
    implementation = _cloudformation_aws_logs_log_group_impl,
    doc = "Schema-derived rule for one `logs_log_group` entry.",
    provides = [CloudformationAwsLogsLogGroupInfo],
    attrs = {
        "logs_log_group_name": attr.string(
            doc = "Top-level key for this logs_log_group in the rendered project. Defaults to the rule name.",
        ),
        "BearerTokenAuthenticationEnabled": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-bearertokenauthenticationenabled (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "DataProtectionPolicy": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-dataprotectionpolicy (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "DeletionProtectionEnabled": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-deletionprotectionenabled (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "FieldIndexPolicies": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-fieldindexpolicies (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "KmsKeyId": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-kmskeyid",
        ),
        "LogGroupClass": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-loggroupclass",
        ),
        "LogGroupName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-loggroupname",
        ),
        "ResourcePolicyDocument": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-resourcepolicydocument (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "RetentionInDays": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-retentionindays (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-loggroup.html#cfn-logs-loggroup-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
    },
)

CloudformationAwsLogsLogStreamInfo = provider(
    doc = "A logs_log_stream contributed by a target. Shard JSON matches the logs_log_stream schema.",
    fields = {
        "logs_log_stream_name": "string: top-level key for this logs_log_stream in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_logs_log_stream_impl(ctx):
    item_name = ctx.attr.logs_log_stream_name or ctx.label.name
    payload = {
        "LogGroupName": ctx.attr.LogGroupName,
        "LogStreamName": ctx.attr.LogStreamName,
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".logs_log_stream.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsLogsLogStreamInfo(logs_log_stream_name = item_name, json = shard),
    ]

cloudformation_aws_logs_log_stream = rule(
    implementation = _cloudformation_aws_logs_log_stream_impl,
    doc = "Schema-derived rule for one `logs_log_stream` entry.",
    provides = [CloudformationAwsLogsLogStreamInfo],
    attrs = {
        "logs_log_stream_name": attr.string(
            doc = "Top-level key for this logs_log_stream in the rendered project. Defaults to the rule name.",
        ),
        "LogGroupName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-logstream.html#cfn-logs-logstream-loggroupname",
        ),
        "LogStreamName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-logs-logstream.html#cfn-logs-logstream-logstreamname",
        ),
    },
)

CloudformationAwsCloudwatchAlarmInfo = provider(
    doc = "A cloudwatch_alarm contributed by a target. Shard JSON matches the cloudwatch_alarm schema.",
    fields = {
        "cloudwatch_alarm_name": "string: top-level key for this cloudwatch_alarm in the rendered project.",
        "json": "File: the JSON shard.",
    },
)

def _cloudformation_aws_cloudwatch_alarm_impl(ctx):
    item_name = ctx.attr.cloudwatch_alarm_name or ctx.label.name
    payload = {
        "ActionsEnabled": parse_json_or_none(ctx.attr.ActionsEnabled),
        "AlarmActions": parse_json_or_none(ctx.attr.AlarmActions),
        "AlarmDescription": ctx.attr.AlarmDescription,
        "AlarmName": ctx.attr.AlarmName,
        "ComparisonOperator": ctx.attr.ComparisonOperator,
        "DatapointsToAlarm": parse_json_or_none(ctx.attr.DatapointsToAlarm),
        "Dimensions": parse_json_or_none(ctx.attr.Dimensions),
        "EvaluateLowSampleCountPercentile": ctx.attr.EvaluateLowSampleCountPercentile,
        "EvaluationCriteria": parse_json_or_none(ctx.attr.EvaluationCriteria),
        "EvaluationInterval": parse_json_or_none(ctx.attr.EvaluationInterval),
        "EvaluationPeriods": parse_json_or_none(ctx.attr.EvaluationPeriods),
        "ExtendedStatistic": ctx.attr.ExtendedStatistic,
        "InsufficientDataActions": parse_json_or_none(ctx.attr.InsufficientDataActions),
        "MetricName": ctx.attr.MetricName,
        "Metrics": parse_json_or_none(ctx.attr.Metrics),
        "Namespace": ctx.attr.Namespace,
        "OKActions": parse_json_or_none(ctx.attr.OKActions),
        "Period": parse_json_or_none(ctx.attr.Period),
        "Statistic": ctx.attr.Statistic,
        "Tags": parse_json_or_none(ctx.attr.Tags),
        "Threshold": parse_json_or_none(ctx.attr.Threshold),
        "ThresholdMetricId": ctx.attr.ThresholdMetricId,
        "TreatMissingData": ctx.attr.TreatMissingData,
        "Unit": ctx.attr.Unit,
    }
    payload = strip_empty(payload)
    shard = ctx.actions.declare_file(ctx.label.name + ".cloudwatch_alarm.json")
    ctx.actions.write(shard, json.encode(payload))
    return [
        DefaultInfo(files = depset([shard])),
        CloudformationAwsCloudwatchAlarmInfo(cloudwatch_alarm_name = item_name, json = shard),
    ]

cloudformation_aws_cloudwatch_alarm = rule(
    implementation = _cloudformation_aws_cloudwatch_alarm_impl,
    doc = "Schema-derived rule for one `cloudwatch_alarm` entry.",
    provides = [CloudformationAwsCloudwatchAlarmInfo],
    attrs = {
        "cloudwatch_alarm_name": attr.string(
            doc = "Top-level key for this cloudwatch_alarm in the rendered project. Defaults to the rule name.",
        ),
        "ActionsEnabled": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-actionsenabled (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "AlarmActions": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-alarmactions (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "AlarmDescription": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-alarmdescription",
        ),
        "AlarmName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-alarmname",
        ),
        "ComparisonOperator": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-comparisonoperator",
        ),
        "DatapointsToAlarm": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-datapointstoalarm (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Dimensions": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-dimensions (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "EvaluateLowSampleCountPercentile": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-evaluatelowsamplecountpercentile",
        ),
        "EvaluationCriteria": attr.string(
            doc = "JSON-encoded value. The shard reader deserialises the parsed JSON straight into the typed schema model.",
        ),
        "EvaluationInterval": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-evaluationinterval (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "EvaluationPeriods": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-evaluationperiods (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "ExtendedStatistic": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-extendedstatistic",
        ),
        "InsufficientDataActions": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-insufficientdataactions (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "MetricName": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-metricname",
        ),
        "Metrics": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-metrics (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Namespace": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-namespace",
        ),
        "OKActions": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-okactions (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Period": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-period (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Statistic": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-statistic",
        ),
        "Tags": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-tags (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "Threshold": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-threshold (JSON-encoded; the Rust shard reader parses this verbatim.)",
        ),
        "ThresholdMetricId": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-thresholdmetricid",
        ),
        "TreatMissingData": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-treatmissingdata",
        ),
        "Unit": attr.string(
            doc = "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-cloudwatch-alarm.html#cfn-cloudwatch-alarm-unit",
        ),
    },
)

